version: '3'

services:
  db:
    image: mysql:8.0.27
    env_file: .env
    container_name: kaigolist_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - kaigolist-data:/var/lib/mysql
      - ./volumes/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./volumes/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "${IP}:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kaigolist_phpmyadmin
    env_file: .env
    restart: always
    links:
      - db
    environment:
      PMA_HOST: 'db'
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    depends_on:
      - db
    ports:
      # - "3001:80"
      - "${IP}:3000:80"
    volumes:
      - ./volumes/phpmyadmin/sessions:/sessions

volumes:
  kaigolist-data:


networks:
  default:
    external:
      name: shared
